services:
  postgres:
    image: postgres:latest
    container_name: sexy-pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: miniyt
    volumes:
      - pg_data:/var/lib/postgresql
    networks:
      - pg-network
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - pg-network
    ports:
      - "8080:80"

  localstack:
    image: localstack/localstack
    container_name: mini-yt-localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3,sqs
      AWS_DEFAULT_REGION: ap-south-1
      DEBUG: 1
    volumes:
      - localstack:/var/lib/localstack

volumes:
  pg_data:
  localstack:

networks:
  pg-network:
